server:
  port: 80
spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 139.196.27.155:8848
      config:
        server-addr: 139.196.27.155:8848
        file-extension: yaml