server:
  port: 11000
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.196.27.155:3306/gulimall_wms
    username: root
    password: 123456
  application:
    name: gulimall-ware #feign不支持下划线"_"，支持"-"
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #返回json时间格式化
  cloud:
    nacos:
      discovery:
        server-addr: 139.196.27.155:8848
mybatis-plus:
  mapper-locations: "classpath*:/mapper/**/*.xml"
  global-config:
    db-config:
      id-type: auto #配置主键自增

#配置日志级别
logging:
  level:
    com.zhen.gulimall: debug